export default {
	BULK_DEL_EMP_CON: "Bạn có thực sự muốn xóa {0} nhân viên đã chọn không?",
	BULK_DEL_EMP_SUC: "{0} bản ghi đã bị xóa",
	UPDATE_SUC: "Dữ liệu đã được cập nhật",
	ADD_SUC: "Thêm mới thành công",
	CLONE_SUC: "Nhân bản thành công",
	DEL_EMP_CON: "Bạn có thực sự muốn xóa nhân viên <{0}> không?",
	DEL_SUC: "Bản ghi đã bị xóa",
	UNKNOWN_ERR: "Có lỗi xảy ra. Vui lòng liên hệ Misa để được hỗ trợ.",
	DPM_NOT_EXIST_ERR: "Đơn vị không có trong danh sách",
	REQUIRED_ERR: "Không được để trống {0}",
	EMP_CODE_INVALID_ERR: "Mã nhân viên phải theo định dạng NV-X (X là số)",
	DATE_GREATER_THAN_TODAY_ERR: "{0} không được lớn hơn ngày hiện tại",
	FORM_CHANGE_WARN: "Dữ liệu đã bị thay đổi. Bạn có muốn cất không?",
	DPM: "Đơn vị",
	EMP_FULLNAME: "Tên nhân viên",
	EMP_CODE: "Mã nhân viên",
	DATE_OF_BIRTH: "Ngày sinh",
	INDENTITY_DATE: "Ngày cấp",
	GENDER: "Giới tính",
	POSITION: "Chức vụ",
	IDENTITY_NUMBER: "Số CMND",
	IDENTITY_PLACE: "Nơi cấp",
	BANK_ACC_NUMBER: "Số tài khoản",
	BANK_NAME: "Tên ngân hàng",
	BANK_BRANCH_NAME: "Chi nhánh TK ngân hàng",
	ADDRESS: "Địa chỉ",
	PHONE_NUMBER: "ĐT di động",
	TELEPHONE_NUMBER: "ĐT cố định",
	EMAIL: "Email",
	DPM_NAME: "Tên đơn vị",
	CREATED_DATE: "Ngày tạo",
	CREATED_BY: "Người tạo",
	MODIFIED_DATE: "Ngày sửa",
	MODIFIED_BY: "Người sửa",
	ITEMS_PER_PAGE: "{0} bản ghi trên 1 trang",
	DPM_CODE: "Mã đơn vị",
	COL_NAME: "Tên cột dữ liệu",
	EMAIL_ERR: "Email không hợp lệ",
};
