//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Misa.Amis.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Misa.Amis.Core.Resources.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên.
        /// </summary>
        public static string DPEmployeeCode {
            get {
                return ResourceManager.GetString("DPEmployeeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nữ.
        /// </summary>
        public static string DPGenderFemale {
            get {
                return ResourceManager.GetString("DPGenderFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nam.
        /// </summary>
        public static string DPGenderMale {
            get {
                return ResourceManager.GetString("DPGenderMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không xác định.
        /// </summary>
        public static string DPGenderUnknown {
            get {
                return ResourceManager.GetString("DPGenderUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ.
        /// </summary>
        public static string DPNAddress {
            get {
                return ResourceManager.GetString("DPNAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số tài khoản.
        /// </summary>
        public static string DPNBankAccountNumber {
            get {
                return ResourceManager.GetString("DPNBankAccountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên chi nhánh.
        /// </summary>
        public static string DPNBankBranchName {
            get {
                return ResourceManager.GetString("DPNBankBranchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên ngân hàng.
        /// </summary>
        public static string DPNBankName {
            get {
                return ResourceManager.GetString("DPNBankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người tạo.
        /// </summary>
        public static string DPNCreatedBy {
            get {
                return ResourceManager.GetString("DPNCreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày tạo.
        /// </summary>
        public static string DPNCreatedDate {
            get {
                return ResourceManager.GetString("DPNCreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày hiện tại.
        /// </summary>
        public static string DPNCurrentDate {
            get {
                return ResourceManager.GetString("DPNCurrentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày sinh.
        /// </summary>
        public static string DPNDateOfBirth {
            get {
                return ResourceManager.GetString("DPNDateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn vị.
        /// </summary>
        public static string DPNDepartment {
            get {
                return ResourceManager.GetString("DPNDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã đơn vị.
        /// </summary>
        public static string DPNDepartmentCode {
            get {
                return ResourceManager.GetString("DPNDepartmentCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đơn vị.
        /// </summary>
        public static string DPNDepartmentName {
            get {
                return ResourceManager.GetString("DPNDepartmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string DPNEmail {
            get {
                return ResourceManager.GetString("DPNEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhân viên.
        /// </summary>
        public static string DPNEmployee {
            get {
                return ResourceManager.GetString("DPNEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chức vụ.
        /// </summary>
        public static string DPNEmployeePosition {
            get {
                return ResourceManager.GetString("DPNEmployeePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ tên nhân viên.
        /// </summary>
        public static string DPNFullName {
            get {
                return ResourceManager.GetString("DPNFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giới tính.
        /// </summary>
        public static string DPNGender {
            get {
                return ResourceManager.GetString("DPNGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nơi cấp.
        /// </summary>
        public static string DPNIndentityPlace {
            get {
                return ResourceManager.GetString("DPNIndentityPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày cấp.
        /// </summary>
        public static string DPNIndetityDate {
            get {
                return ResourceManager.GetString("DPNIndetityDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số CMND.
        /// </summary>
        public static string DPNIndetityNumber {
            get {
                return ResourceManager.GetString("DPNIndetityNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người sửa.
        /// </summary>
        public static string DPNModifiedBy {
            get {
                return ResourceManager.GetString("DPNModifiedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày sửa.
        /// </summary>
        public static string DPNModifiedDate {
            get {
                return ResourceManager.GetString("DPNModifiedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại.
        /// </summary>
        public static string DPNPhoneNumber {
            get {
                return ResourceManager.GetString("DPNPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại cố định.
        /// </summary>
        public static string DPNTelephoneNumber {
            get {
                return ResourceManager.GetString("DPNTelephoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy {0}.
        /// </summary>
        public static string EMResourceNotFound {
            get {
                return ResourceManager.GetString("EMResourceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra. Vui lòng liên hệ Misa để được hỗ trợ.
        /// </summary>
        public static string EMServerError {
            get {
                return ResourceManager.GetString("EMServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách {0}.
        /// </summary>
        public static string ExcelTitle {
            get {
                return ResourceManager.GetString("ExcelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin {0} không đúng định dạng email.
        /// </summary>
        public static string VEMEmail {
            get {
                return ResourceManager.GetString("VEMEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} đã tồn tại.
        /// </summary>
        public static string VEMExisted {
            get {
                return ResourceManager.GetString("VEMExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} không được lớn hơn {1}.
        /// </summary>
        public static string VEMLessThan {
            get {
                return ResourceManager.GetString("VEMLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} không tồn tại.
        /// </summary>
        public static string VEMNotExisted {
            get {
                return ResourceManager.GetString("VEMNotExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin {0} không đúng định dạng số điện thoại.
        /// </summary>
        public static string VEMPhoneNumber {
            get {
                return ResourceManager.GetString("VEMPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin {0} phải nằm trong khoảng {1}-{2}.
        /// </summary>
        public static string VEMRange {
            get {
                return ResourceManager.GetString("VEMRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin {0} không khớp định dạng {1}.
        /// </summary>
        public static string VEMRegular {
            get {
                return ResourceManager.GetString("VEMRegular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin {0} không được để trống.
        /// </summary>
        public static string VEMRequired {
            get {
                return ResourceManager.GetString("VEMRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin {0} không được có nhiều hơn {1} ký tự.
        /// </summary>
        public static string VEMStringLength {
            get {
                return ResourceManager.GetString("VEMStringLength", resourceCulture);
            }
        }
    }
}
